# sheet
- id: "yeoldesheet"
  driverName: "legacySheet"
  args: {}
# RDL
- id: "rdl"
  driverName: "discord"
  args:
    # environment variables are inserted like this
    botToken: "{env!DISCORD_BOT_TOKEN}"
    channelID: "611380148431749151"
    after: "812128531924385813"
# Steam Workshop
- id: "workshop"
  driverName: "workshop"
  args:
    bluebell: "http://127.0.0.1:8000"