# fly.toml file generated for orchard-bot-main on 2022-11-07T10:09:48Z

app = "orchard-bot-main"
kill_signal = "SIGTERM"
kill_timeout = 10
processes = []

[deploy]
  strategy = "rolling"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 99
    soft_limit = 90
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
