name: Deploy the bot

on:
  push:
    branches: [ main ]
    paths:
      - 'orchard/bot/**'
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install flyctl
      uses: superfly/flyctl-actions/setup-flyctl@master

    - name: set up secrets
      run: flyctl secrets set --config ./orchard/bot/fly.toml LITESTREAM_ACCESS_KEY_ID=${{ secrets.B2_KEY_ID }} LITESTREAM_SECRET_ACCESS_KEY=${{ secrets.B2_APPLICATION_KEY }}
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

    - name: fly me to the moon
      run: flyctl deploy --remote-only --config ./orchard/bot/fly.toml --dockerfile ./orchard/bot/Dockerfile  .
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      working-directory: .
