name: Deploy the bot

on:
  push:
    branches: [ main ]
    paths:
      - 'orchard/bot/**'
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install flyctl
      uses: superfly/flyctl-actions/setup-flyctl@master

    - name: set up secrets
      run: >
        flyctl secrets set --config ./orchard/bot/fly.toml
        LITESTREAM_ACCESS_KEY_ID=${{ secrets.B2_LITESTREAM_KEY_ID }}
        LITESTREAM_SECRET_ACCESS_KEY=${{ secrets.B2_LITESTREAM_SECRET }}
        BOT_TOKEN=${{ secrets.BOT_TOKEN }}
        PUBLIC_KEY=${{ secrets.PUBLIC_KEY }}
        APPLICATION_ID=${{ secrets.APPLICATION_ID }}
        DEV_GUILD=${{ secrets.DEV_GUILD }}
        PATHLAB_ROLE=${{ secrets.PATHLAB_ROLE }}
        SECRET_KEY_ORCH=${{ secrets.SECRET_KEY_ORCH }}
        POST_STATUS_DOT_DB_TOKEN=${{ secrets.POST_STATUS_DOT_DB_TOKEN }}
        TYPESENSE_URL=https://api.rhythm.cafe/typesense
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      continue-on-error: true
      working-directory: .

    - name: fly me to the moon
      run: flyctl deploy --remote-only --config ./orchard/bot/fly.toml --dockerfile ./orchard/bot/Dockerfile  .
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      working-directory: .
