# todo: download current status.db and upload it to new instance.

name: Deploy the bot

on:
  push:
    branches: [ main ]
    paths:
      - 'orchard/bot/**'
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: DigitalOcean App Platform deployment
      uses: digitalocean/app_action@main
      with:
        app_name: orchard-bot
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
