# Copy files by name on b2

name: B2 copy file

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      from:
        description: File name to copy from
        required: true
        type: string
      to:
        description: File name to copy to
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  copy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: install b2
        run: pipx install b2
        
      - name: configure b2
        run: b2 authorize-account $B2_KEY_ID $B2_APPLICATION_KEY
        env:
          B2_APPLICATION_KEY: ${{ secrets.B2_APPLICATION_KEY }}
          B2_KEY_ID: ${{ secrets.B2_KEY_ID }}

      - name: download from file
        run: b2 download-file-by-name rdcodex ${{ github.events.input.from }} TEMPFILE
        
      - name: upload
        run: b2 upload-file rdcodex TEMPFILE ${{ github.events.input.to }}
