# This is a basic workflow to help you get started with Actions

name: Index

# only one run instance of the indexer at a time.
concurrency: sqlite3

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  # run hourly
  schedule:
    - cron: "14 * * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      ### STEAMCMD ###

      # Preseed agreement to the Steam Licence Agreement
      - name: Preseed agreement to Steam Licence Agreement
        run: |
          echo steam steam/question select "I AGREE" | sudo debconf-set-selections
          echo steam steam/license note '' | sudo debconf-set-selections
          
      # Install SteamCMD, will this really work??
      - name: Install SteamCMD
        run: |
          sudo add-apt-repository multiverse
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install lib32gcc1 steamcmd 
          
      # Runs SteamCMD once so it can upgrade itself
      - name: Run SteamCMD once so it upgrades itself
        run: steamcmd +quit

      ### BLUEBELL ###
      
      # install python3 stuff
      - name: Install python3
        run: sudo apt-get -y install libarchive-tools python3 python3-pip curl sqlite3 python-is-python3
        
      # install node stuff
      - name: Setup node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ">=15"
          
      - name: Install PM2
        run: sudo npm install pm2 -g

      # install bluebell prereqs
      - name: Install bluebell prereqs
        run: sudo pip3 install sanic scrapy dateparser rsa
        
      # clone bluebell
      - name: clone bluebell
        run: git clone https://github.com/auburnsummer/bluebell.git
        
      # ls
      - name: run bluebell as a PM2 process
        working-directory: ./bluebell
        run: pm2 start main.py --name bluebell 
        env:
          STEAM_USER: ${{ secrets.STEAM_USER }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
        
      # test
      - name: Testing bluebell is working
        run: sleep 10 && curl localhost:8000/774181/levels
        
      ### FLYCTL ###
      
      - name: Install flyctl
        run: curl -L https://fly.io/install.sh | sh
        
      - name: Update flytcl path
        run: echo /home/runner/.fly/bin >> $GITHUB_PATH
          
      - name: test
        run: echo $PATH

      - name: Check current status
        run: flyctl status --app orchard
        env:
          FLY_ACCESS_TOKEN: ${{ secrets.FLY_ACCESS_TOKEN }}
          
      ### DATASETTE ###
      
      - name: Install Datasette
        run: sudo pip3 install datasette datasette-publish-fly
      
      ### RD INDEXER ###

      - name: Install dependencies
        run: npm install

      - name: Download the current db
        run: mkdir db && curl http://api.rhythm.cafe/orchard.db > db/orchard.db
        
      - name: Make a copy of it for later
        run: cp db/orchard.db db/orchard_orig.db
        
      - name: Print out the sha1sum of the current db
        run: sha1sum db/orchard.db
        
      - name: The index!
        run: timeout 15m node lib/cli.js db/orchard.db conf/sources.yml || true
        env:
          B2_APPLICATION_KEY: ${{ secrets.B2_APPLICATION_KEY }}
          B2_BUCKET_ID: ${{ secrets.B2_BUCKET_ID }}
          B2_KEY_ID: ${{ secrets.B2_KEY_ID }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          HOSTED_FILES_PREFIX: ${{ secrets.HOSTED_FILES_PREFIX }}
          
      - name: merge, for now it's like this
        run: |
          cp db/orchard.db db/orchard1.db
          node lib/cli.js merge db/orchard.db db/orchard1.db
          
      - name: Print out the diff
        run: sqldiff --primarykey db/orchard.db db/orchard_orig.db
        
      - name: Publish using Datasette
        run: datasette publish fly db/orchard.db --app="orchard"
        env:
          FLY_ACCESS_TOKEN: ${{ secrets.FLY_ACCESS_TOKEN }}
        
      - name: See how the pm2 logs are doing
        run: pm2 logs --lines 99999 --nostream
