# This is a basic workflow to help you get started with Actions

name: uhhh

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  hmm:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: install pypy
        id: setup-pypy
        uses: actions/setup-python@v3
        with:
          python-version: 'pypy-3.8'
          cache: 'poetry'

      - name: install deps 
        run: poetry install --no-interaction

      - name: download the problematic level
        run: curl https://cdn.discordapp.com/attachments/611380148431749151/1006805725558874153/a_bad_apple_a_day_keeps_the_rhythm_doctor_away.rdzip > apple.rdzip
        working-directory: ./orchard/vitals

      - name: extract it?
        run: unzip apple.rdzip
        working-directory: ./orchard/vitals
        
      - name: ls
        run: ls
